### ISSUE TITLE
G4.114 Update validation feedback shown to the user

### ISSUE THREAD

**Issue by carolyncaron** [TripalCultivate/TripalCultivate-Phenotypes#114]
### Branch

g4.114-updateValidationFeedback
g4.114-updateProcessMessages

### Groups

Group 4 - API | Services | Plugins

### Describe

This issue is meant to address the overall design of how validation statuses and messages get relayed back to the user.

This is where the current design is at previous to our current milestone for this module:
![image](https://github.com/user-attachments/assets/75683aa8-6a45-4e14-af30-b7400e202d51)

### Design

We (@laceysanderson, @reynoldtan, @ruobinLiu and I) held a meeting to discuss what we'd like to see, both in terms of how it should look for all importers, and specifically the needs of the Traits Importer. These are the things we decided that can begin to be implemented and we can reconvene as needed:

- [x] Update the feedback "engine" to expect a render array from each feedback item (which may include feedback from 1+ validators)
- [x] To update the processValidationMessages() method in `TraitsImporter` to format the messages we want the user to see. We may need to entertain additional methods either in the `TraitsImporter` class or to the individual validator classes to prevent the code from being too overwhelming
- [x] We think that continuing to use status icons (representing pass/fail/todo) are helpful and even colour-coding if applicable

**Comment by laceysanderson** [comment]
## Feedback Render Engine

This will render the display to the user providing feedback.

Currently it takes an array structure where each item in the array is a **Feedback Item**:
 - title: this is always displayed to the user regardless of status and is a short title describing what validation was done.
 - status: one of 'pass', 'fail', 'todo' and indicates which icon to be displayed in front of the title.
 - details: currently this is a simple string that describes what failed and is only present if the status is 'fail'. **NEW: we want this to be a render array**

Changes are that the Feedback Render Engine will simply pass the render array it is given to the Drupal Render API. The result from the render API will then be embedded in the markup required to indent it within that feedback item. The Feedback Render Engine only cares about the markup wrapping whatever is returned from the Drupal render engine.

![IMG_1431](https://github.com/user-attachments/assets/be5a36f2-8991-42a4-8004-ee5fd33b9f00)

### Tasks

 - [x] Decide on the design of the validation window
 - [x] determine markup needed to wrap details render array to achieve that
 - [x] Research drupal render engine to get it to render the render array

## Process Messages

This is the task of going from developer validation results returned from the validators to a user friendly feedback of failures which is described by a render array (i.e. this is `developer case` + `failedItems` => `Render Array`). 

### Tasks

 - [x] Design what we want the render array to be for each validation item in the trait importer. This is to make a list of each one and decide what should be displayed if it fails. Explore different render array #types for each validation item, although obviously types can be repeated. We may also want different render array types for different cases.
 - [ ] Separate the row-level message processing (e.g. empty cell, duplicate traits) from the one-time message processing (e.g. metadata, file, header).
 - [ ] Design how to combine multiple different render arrays if multiple cases are triggered. Remember that render arrays are nestable and that each validation item can only have one render array returned.
 - [ ] Design how to go from multiple row-level validation errors for a single validator to a single, user friendly render array.
     - add a method to each validator that is given tokens (e.g. line numbers, context token) and the failures array and knows how to generate the render array for that particular validator
     - have methods in the trait importer that handle this. This is essentially an offload the logic approach while keeping everything in the importer to keep the "Cognitive Complexity" ghost away.
     - if we find that a validator-specific method is too restrictive (e.g if we want to combine multiple validator failures into a single freedback item) then we may want to design a feedback item plugin type which can handle this. 

But we don't want to over engineer before we really know what we need.

**Comment by carolyncaron** [comment]
Commit [ff68576](https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/116/commits/ff68576ada5904c1cc3f2930476289682ccf0089) of PR #91 removes an array keeping track of various counts in the Traits Importer, such as rows failing validation. This was done since it currently isn't needed anywhere in the code and we don't want it to become a remnant. However, a lot of time was put into making the array and there is a chance we will find it useful once this issue starts being implemented. I created a patch here:
[count_rows_validation.patch](https://github.com/user-attachments/files/17593019/count_rows_validation.patch)

If needed, it can be applied using: `git apply count_rows_validation.patch`
If it does not apply (potentially because the code has diverged too much) then you can open the patch and copy and paste whatever is needed from there.

**Comment by reynoldtan** [comment]
![image](https://github.com/user-attachments/assets/42fa0718-4252-4dc4-8c30-99f5509bc62b)

- Current setup as is the previous version of importers using validation result window.
- Familiar user interface.

Markup structure:
```
// The main window container.
<details>  
  // Text shown in the window/container title bar.
  <summary>Validation Result Window</summary>
 
  // List validation result items.
  <li>
    This is a validation item text/title.
    Details about the failed item (if it returned a failed status)
  <li>
   
   ...
</details>
```



![image](https://github.com/user-attachments/assets/7fbf60f3-9485-4a40-8083-87598b00b0df)

- Familiar user interface that functions similarly to the importer form for PhenoCollect (accordion).
- Incorporate additional visual cues like highlighting the failed stack.
- Collapsible and expandable elements.

Markup structure:

```
// Single validation item stack.
<details>
  <summary>Validation text/title</summary>
  
   Details about the failed item (if it returned a failed status)
</details>
...

```
Using jQuery Accordion UI
[https://jqueryui.com/accordio](https://jqueryui.com/accordion)




![image](https://github.com/user-attachments/assets/7402e8dd-182f-4db4-ad8f-68b3e09a595f)

- Organized results into 2 tabs
- More visual cues ie. # of failed items, one line upload status and pre-select tab.
- Tab content area can accommodate details with complex display format.

Markup structure:

```
<div>
   // Tabs.
   <ul>
    <li>Passed Items</a>
    <li>Failed Items</a>
   </ul>
   
    // Tab containers.
    <div>
      Items that passed.
    </div>
    
    <div>
      Items that failed.
    </div>
</div>

```
Using jQuery Tabs UI
[https://jqueryui.com/tabs/](https://jqueryui.com/tabs)

**Comment by reynoldtan** [comment]
```

// Failed data rows:
// This example renders an unordered list with a table for each item describing two cases.
$validation_item = [
  'title' => 'Validation Title',
  'status' => 'fail',
  'details' => [
    '#type' => 'html_tag',
    '#tag' => 'ul',
    0 => [
      '#type' => 'html_tag',
      '#tag' => 'li',
      [
        '#type' => 'table',
        '#caption' => 'Case One',
        '#header' => ['Line number', 'message'],
        '#rows' => [
          [5, 'failed item'],
          [6, 'failed item'],
          [7, 'failed item'],
        ],
      ],
    ]
    1 => [
      '#type' => 'html_tag',
      '#tag' => 'li',
      [
        '#type' => 'table',
        '#caption' => 'Case Two',
        '#header' => ['Line number', 'message'],
        '#rows' => [
          [2, 'failed item'],
        ],
      ],
    ],
  ],
];

// Failed Metadata:
$validation_item = [
    'title' => 'Validation Title',
    'status' => 'pass',
    'details' => [
        [
          '#type' => 'html_tag',
          '#tag' => 'p',
          0 => [
            '#type' => 'item',
            '#title' => 'case name',
            '#markup' => 'The genus entered was not configured to work with Phenotypes. Please get your administrator to configure this genus for you and then try again.',
          ],
       ],
    ],
];


// Passed:
$validation_item = [
    'title' => 'Validation Title',
    'status' => 'pass',
    'details' => []
];


// Todo:
$validation_item = [
    'title' => 'Validation Title',
    'status' => 'todo',
    'details' => []
];


// To render details:
$details = \Drupal::service('renderer')
  ->render($validation_item['details']);
```

References:
 - Existing render array types: https://api.drupal.org/api/drupal/namespace/Drupal%21Core%21Render%21Element/11.x

**Comment by reynoldtan** [comment]
### **ITEM:**
- with one failed item value

Mockup of failed validation error details:

![image](https://github.com/user-attachments/assets/4a1849f7-9628-411a-bc52-96e150f7bcfc)


Failed details render array structure:
#type is set to **item**
```
$validation_item = [
   ...

  'details' => [
    '#type' => 'item',
    '#title'  => 'Validator Case Message',
    '#markup' => 'Failed Item Name: Failed Item Value'
  ]
];
```

Render array markup: 
```
<div>
  <label>Validator Case Message</label>
  Failed Item Name: Failed Item Value
</div>
```


Actual render array output (in the current theme Gin).

<img width="718" alt="image(4)" src="https://github.com/user-attachments/assets/c8d45975-6fe0-482f-b537-f1dfc5158ba3">

- with multiple failed item values

![image](https://github.com/user-attachments/assets/1895f3f5-2dd4-4185-9ee0-61d573817740)


Failed details render array structure:
#type is set to **item**
```
$validation_item = [
   ...

  'details' => [
    '#type' => 'item',
    '#title'  => 'Validator Case Message',
    'failed_items' => [
      [
        '#markup' => 'Failed Item Value 1, ' // Comma symbol
      ],
      [
        '#markup' => 'Failed Item Value 2, ' // Comma symbol
      ],
      [
        '#markup' => 'Failed Item Value 3'  // No comma symbol (last item).
      ]
    ]
  ]
];
```

Render array markup: 
```
<div>
  <label>Validator Case Message</label>
  Failed Item Value 1, Failed Item Value 2, Failed Item Value 3
</div>
```

Actual render array output (in the current theme Gin).
<img width="729" alt="image(6)" src="https://github.com/user-attachments/assets/b21dfdc5-d1e7-48b6-89ca-b0cb7c0aa910">


### **LIST + TABLE**

Mockup of failed validation error details:
![image](https://github.com/user-attachments/assets/4105c3cc-ecc2-42a7-b4be-72ca973e08e0)

Failed details render array structure:
#type is set to **ul + table**
```
$validation_item = [
   ...

  'details' => [
    '#type' => 'html_tag',
    '#tag' => 'ul',
    'lists' => [
      [
        '#type' => 'html_tag',
        '#tag' => 'li',
        'table' => [
          '#type' => 'table',
          '#caption' => 'Validator Case Message',
          '#header' => ['Line Number', 'Message/Failed Item/Failed Value'],
          '#rows' => [
            [2, 'Failed Value'],
            [3, 'Failed Value'],
            [4, 'Failed Value'],
            [5, 'Failed Value'],
          ]
        ]
      ],
      [
        '#type' => 'html_tag',
        '#tag' => 'li',
        'table' => [
          '#type' => 'table',
          '#caption' => 'Validator Case Message #1',
          '#header' => ['Line Number', 'Message/Failed Item/Failed Value'],
          '#rows' => [
            [6, 'Failed Value'],
            [7, 'Failed Value'],
            [8, 'Failed Value'],
          ]
        ]     
      ],
    ]   
  ]
];
```

**NOTE:**
The #header can be more than just the line number and the message/failed item or value.

For example:
Duplicate Traits Validator:
```
#header = ['Line Number', 'Trait Name', 'Method Short Name', 'Unit'];
#rows = [
  ['Line Number', 'Trait Name #1', 'Trait #1 Method Short Name', 'Trait #1 Unit'],
  ['Line Number', 'Trait Name #2', 'Trait #2 Method Short Name', 'Trait #2 Unit'], 
  ...
];
```
<img width="785" alt="image" src="https://github.com/user-attachments/assets/ba432b12-fa4d-4eb4-b2b7-5cbdd8bd0f58">



Render array markup: 
```
<ul>
  <li>
    <table>
      <caption>Validation Case Message</caption>
      <thead>
       <tr>
        <td>Line Number</td>
        <td>Message/Failed Item/Failed Value</td> 
      </tr> 
     </thead>
      
      <tbody>
        <tr>
          <td>2</td>
          <td>Failed Item</td>
        <tr>

       ...
      </tbody>
    </table>
    
    <li></li>
    <li></li>
    ...
  </li>
</ul>
```


Actual render array output (in the current theme Gin).

<img width="714" alt="image(5)" src="https://github.com/user-attachments/assets/6a097076-deab-4307-b115-de09672c8eeb">

(🤔 could there be validation item with multiple cases?)

### **Validator to render type:**

ITEM - one failed item value:
1. Genus
2. Project
3. Data File

ITEM (bulleted list) - multi-failed item values:
1. Headers

List+Table
1. ValidDelimitedFile (returns the whole raw row if fails - maybe want the table to be scrollable, and add html tag to show tab delimiter)
2. Duplicate Traits
3. Empty Cell
4. Value In List

**Comment by reynoldtan** [comment]
### **ITEM + LIST:**
details is displayed as an unordered list

Failed details render array structure:
#type is set to **item**
```
$validation_item = [
   ...

  'details' => [
    '#type' => 'item',
    '#title'  => 'Validator Case Message',
    'failed_items' => [
      '#theme' => 'item_list',
      '#type' => 'ul',
      '#items' => [
        'Failed Item Value #1',
        'Failed Item Value #2',
        'Failed Item Value #3'
      ]  
    ]
  ]
];
```

Render array markup: 
```
<div>
  <label>Validator Case Message</label>
  <div class="item-list">
    <ul>
      <li>Failed Item Value #1</li>
      <li>Failed Item Value #2</li>
      <li>Failed Item Value #3</li>
    </ul>
  </div>
</div>
```

Actual render array output (in the current theme Gin).
<img width="634" alt="image" src="https://github.com/user-attachments/assets/a2f5e6af-2c66-45cb-94ee-c0623bfa1551">

**Comment by reynoldtan** [comment]
Testing the idea if a validator can produce 2 case messages:
Setup:

A Trait data file that has the unit type set to blank/empty value to trigger that it has an empty value and the value is not Quantitative nor Qualitative.

Data file:
<img width="705" alt="image" src="https://github.com/user-attachments/assets/d79f735a-2ea9-4553-bfc9-4b4c875d543f">


Output:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/a09a5ee2-d5dc-4b36-9e48-0765a0f8b837">

**Comment by reynoldtan** [comment]
Testing long failed item value:

Failed details render array:


```
$render = [
      '#type' => 'html_tag',
      '#tag' => 'ul',
      'lists' => [
        [
          '#type' => 'html_tag',
          '#tag' => 'li',
          'table' => [
            '#type' => 'table',
            '#caption' => 'Validator Case Message',
            '#header' => ['Line Number', 'Message/Failed Item/Failed Value'],
            '#rows' => [
              [1, [
                'data' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis efficitur sem at augue facilisis mollis. Etiam in nisi at lectus placerat vulputate non vitae eros. Curabitur eu mattis quam. Donec vitae vehicula enim.',
                'style' => 'text-overflow: ellipsis; white-space: nowrap; overflow: hidden'
                ]
              ],
            ]
          ]
        ],
      ]
    ];

```

Actual render array output (in the current theme Gin).

Default:
<img width="743" alt="image" src="https://github.com/user-attachments/assets/9204e50c-4e0a-45bf-b17b-28497973ef45">

With nowrap rule
<img width="744" alt="image" src="https://github.com/user-attachments/assets/96299b33-3bd7-48a4-aa78-dfd0e61eb3d9">

For ellipsis to work ie:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis efficitur sem...

- The container element of the text must have a definite width. Overflow will be set to hidden and ellipsis is the value for text-overflow rule.

``
.text-clip {
  width: 200px
  overflow: hidden;
  text-overflow: ellipsis;
}
``

<img width="599" alt="image" src="https://github.com/user-attachments/assets/413d6ff7-c86c-44b6-ad9b-a6ce43beb8a2">

**Comment by reynoldtan** [comment]
This is a mockup of empty cell and value in list validators:

<img width="806" alt="image" src="https://github.com/user-attachments/assets/44885304-8a10-43f6-87f8-281fa6f1d8f7">
Failed details render array:

```
// Indices returned by empty cell validator.
$failed_indices = [0, 2, 3, 4];
// Headers array simplified to only contain the headers + index.
$headers = array_column($this->headers, 'name');

$resolved_indices = array_map(function($index) use($headers) {
  return $headers[$index];
}, $failed_indices);

$render = [
  '#type' => 'html_tag',
  '#tag' => 'ul',
  'lists' => [
    [
      '#type' => 'html_tag',
      '#tag' => 'li',
      'table' => [
        '#type' => 'table',
        '#caption' => 'Validator Case  - Empty Cell',
        '#header' => ['Line Number', 'Column Header(s)/Column Indices'],
        '#rows' => [
          [1, 'Header 1'],
          [2, 'Header 1, Header 2'],
          [3, 'Header 3, Header 4, Header 5, Header 6'],
          [4, 'Header 4'],
          [7, implode(', ', $resolved_indices) . ' * '],
          [8, implode(', ', $failed_indices) . ' * '],
        ]
      ]
    ]
  ]
];

```

<img width="805" alt="image" src="https://github.com/user-attachments/assets/5ad122ed-feb4-4a96-83b8-2f4c4caa7f5f">

```
// Failed array returned by value in list. 
$failed = [4 => 'quantitative'];
// Headers array simplified to only contain the headers + index.
$headers = array_column($this->headers, 'name');

$resolved_index = $headers[key($failed)];

$render = [
  '#type' => 'html_tag',
  '#tag' => 'ul',
  'lists' => [
    [
      '#type' => 'html_tag',
      '#tag' => 'li',
      'table' => [
        '#type' => 'table',
        '#caption' => 'Validator Case  - Empty Cell',
        '#header' => ['Line Number', 'Column Header(s)/Column Indices', 'Value'],
        '#rows' => [
          [1, 'Header 1', 'qualitative'],
          [7, $resolved_index, $failed[key($failed)]],
          [8, key($failed), $failed[key($failed)]]
        ]
      ]
    ]
  ]
];
```

Trigger a scroll bar when more item in the window:
<img width="808" alt="image" src="https://github.com/user-attachments/assets/a762d57f-4831-4249-beb3-2b1a4fcb3529">


Other theme:
Olivero:
<img width="747" alt="image" src="https://github.com/user-attachments/assets/d5028e3f-5810-4415-a63b-3df67fbef945">

Default:
<img width="664" alt="image" src="https://github.com/user-attachments/assets/c64ca7bb-ec86-488b-98f8-ccf980b35232">

**Comment by laceysanderson** [comment]
This diagram shows the workflow and the separation of tasks between Carolyn + Reynold.

![Workflow](https://github.com/user-attachments/assets/95bbedb2-a8a2-4746-86d4-1452a5dd5ed3)

**Comment by reynoldtan** [comment]
Render array type and markup output:
<img width="662" alt="image" src="https://github.com/user-attachments/assets/d19f9caf-9b8f-4e0b-ab9b-6cf1537a7826">

**1: Passing/todo or no failed items:**
```
[
  'title' => 'Validation Title',
  'status' => 'pass | todo',
  'details' => []
]
```
2: Failed validator with single or multiple failed items: 
```
[
  'title' => 'Validation Title',
  'status' => 'fail',
  'details' => [
    '#type' => 'item',
    '#title' => 'Validator case message',
    'items' => [
      '#theme' => 'item_list',
      '#type' => 'ul',
      '#items' => [
        'Failed Item 1', 
        'Failed Item 2',
        ...
      ]
    ]
  ]
]
```
3 & 4: Tabled failed items:
```
[
  'title' => 'Validation Title',
  'status' => 'fail',
  'details' => [
    '#type' => 'html_tag',
    '#tag' => 'ul',
    'lists' => [
      [
        '#type' => 'html_tag',
        '#tag' => 'li',
        'table' => [
          '#type' => 'table',
          '#caption' => 'Validator case message',
          '#header' => ['Header 1, 'Header 2', ...],
          '#attributes' => [],
          '#rows' => [
            ['Value 1', 'Value 2' ...],
            [Value 1'], 'Value 2' ...]
             ... 
          ]
        ]
      ],
      ... 
     ] 
   ]
]
```

Note: implement an #attributes property when setting up a table and use this value to apply a class tcp-raw-row to display text as a preformatted text equivalent to wrapping the text value to pre tag.

5: Single line failed item:
```
[
  'title' => 'Validation Title',
  'status' => 'fail',
  'details' => [
    '#type' => 'item',
    '#title' => 'Validator case message',
    '#markup' => 'Failed Item Name: Failed Item Value'
  ]
]
```

**Comment by reynoldtan** [comment]
This issue has been resolved in PR https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/127 and can be tagged closed.
