### ISSUE TITLE
G4.90 Update trait importer to use only new style validators

### ISSUE THREAD

**Issue by laceysanderson** [TripalCultivate/TripalCultivate-Phenotypes#90]
### Branch

g4.90-updateImporterWithNewValidators

### Groups

Group 2 - Data Importing, Group 4 - API | Services | Plugins

### Dependencies

- #92 
- #93 
- #87
- #88 
- #89 
- #85 

### Describe

Update trait importer to use the new genus, file and header validators by adding them to the configure and removing the old versions. These validators were created in issues #87, #88, and #89. Issue #79 has already laid the groundwork for the importer using the new validators which allows this PR to focus on the config only.

### Tasks

- [ ] Replace the old `genus`, `project`, `datafile` and `headers` validators in the Trait Importer with their new versions. 
- [ ] Update the Trait importer config to use the new setters
- [ ] Update the trait importer formValidate to use the new return value style and ignore the old one. Update any import tests with this in mind. (Only this task needs #85)
- [ ] Update the associated tests related to return value.
